# File: simple-param.yml
parameters:
- name: ID
  type: string
- name: CONFIG_FILE # name of the parameter; required
  type: string
  default: backend-config.json
- name: INFRASTRUCTURE
  type: string
  default: azure-backend-test
- name: STEPS
  type: string
  default: deploy,destroy

trigger: none

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ubuntu-18.04
  steps:
    - task: DownloadSecureFile@1
      name: configPath
      inputs:
        secureFile: ${{ parameters.CONFIG_FILE }}
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          sudo bash ./utils/setup_env.sh
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          python3 ./src/runner.py --config_path $CONFIGPATH_SECUREFILEPATH --terraform_workspace ./test-infra/${{ parameters.INFRASTRUCTURE }} --steps ${{ parameters.STEPS }} --id ${{ parameters.ID }}