parameters:
- name: ID
  type: string
- name: SECRETS_FILE 
  type: string
  default: secrets.json
- name: CONFIG_FILE_URL
  type: string
- name: INFRASTRUCTURE
  type: string
  default: azure-backend-test
- name: STEPS
  type: string
  default: deploy,destroy
- name: CUSTOM_FIELDS
  type: string
  default: none

trigger: none

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ubuntu-18.04
  steps:
    - task: DownloadSecureFile@1
      name: secretsPath
      inputs:
        secureFile: ${{ parameters.SECRETS_FILE }}
    - task: DownloadSecureFile@1
      name: gcpSecret
      inputs:
        secureFile: gcp-seed-sa.json
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          sudo bash ./utils/setup_env.sh
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          wget ${{ parameters.CONFIG_FILE_URL }} -O /tmp/config.json
          if [[ "${{ parameters.CUSTOM_FIELDS }}" != "none" ]];then
              param_fields=";${{ parameters.CUSTOM_FIELDS }}"
          fi

          CUSTOM_FIELDS="secrets.gcp.key-path=$GCPSECRET_SECUREFILEPATH$param_fields"
          echo $CUSTOM_FIELDS

          python3 ./src/runner.py \
                --secrets_path $SECRETSPATH_SECUREFILEPATH \
                --config_path /tmp/config.json \
                --terraform_workspace ./test-infra/${{ parameters.INFRASTRUCTURE }} \
                --steps ${{ parameters.STEPS }} \
                --id ${{ parameters.ID }} \
                --custom_fields "$CUSTOM_FIELDS"